export const teamFlags: Record<string, string> = {
  "Česko": "cz", "Czech Republic": "cz", "CZE": "cz", "Czechia": "cz",
  "Švédsko": "se", "Sweden": "se", "SWE": "se",
  "Kanada": "ca", "Canada": "ca", "CAN": "ca",
  "USA": "us", "United States": "us",
  "Švýcarsko": "ch", "Switzerland": "ch", "SUI": "ch",
  "Finsko": "fi", "Finland": "fi", "FIN": "fi",
  "Německo": "de", "Germany": "de", "GER": "de",
  "Dánsko": "dk", "Denmark": "dk", "DEN": "dk",
  "Norsko": "no", "Norway": "no", "NOR": "no",
  "Slovensko": "sk", "Slovakia": "sk", "SVK": "sk",
  "Slovinsko": "si", "Slovenia": "si", "SLO": "si",
  "Itálie": "it", "Italy": "it", "ITA": "it",
  "Rakousko": "at", "Austria": "at", "AUT": "at",
  "Lotyšsko": "lv", "Latvia": "lv", "LAT": "lv",
  "Maďarsko": "hu", "Hungary": "hu", "HUN": "hu",
  "Velká Británie": "gb", "Great Britain": "gb", "GBR": "gb",
  "Rusko": "ru", "Russia": "ru", "RUS": "ru",
  "Polsko": "pl", "Poland": "pl", "POL": "pl",
  "Francie": "fr", "France": "fr", "FRA": "fr",
  "Japonsko": "jp", "Japan": "jp", "JPN": "jp",
  "Kazachstán": "kz", "Kazakhstan": "kz", "KAZ": "kz",
  "Alžírsko": "dz", "Algeria": "dz", "ALG": "dz",
  "Argentýna": "ar", "Argentina": "ar", "ARG": "ar",
  "Austrálie": "au", "Australia": "au", "AUS": "au",
  "Belgie": "be", "Belgium": "be", "BEL": "be",
  "Bosna a Hercegovina": "ba", "Bosnia and Herzegovina": "ba", "BIH": "ba",
  "Brazílie": "br", "Brazil": "br", "BRA": "br",
  "Kapverdy": "cv", "Cabo Verde": "cv", "CPV": "cv",
  "Kolumbie": "co", "Colombia": "co", "COL": "co",
  "Demokratická republika Kongo": "cd", "Democratic Republic of the Congo": "cd",
  "Chorvatsko": "hr", "Croatia": "hr", "CRO": "hr",
  "Curacao": "cw", "Curaçao": "cw", "CUW": "cw",
  "Pobřeží slonoviny": "ci", "Côte d’Ivoire": "ci", "CIV": "ci",
  "Ekvádor": "ec", "Ecuador": "ec", "ECU": "ec",
  "Egypt": "eg", "EGY": "eg",
  "Anglie": "gb-eng", "England": "gb-eng", "ENG": "gb-eng",
  "Ghana": "gh", "GHA": "gh",
  "Haiti": "ht", "HTI": "ht",
  "Írán": "ir", "IR Iran": "ir", "IRN": "ir",
  "Irák": "iq", "Iraq": "iq", "IRQ": "iq",
  "Jordánsko": "jo", "Jordan": "jo", "JOR": "jo",
  "Korejská republika": "kr", "Korea Republic": "kr", "KOR": "kr",
  "Mexiko": "mx", "Mexico": "mx", "MEX": "mx",
  "Maroko": "ma", "Morocco": "ma", "MAR": "ma",
  "Nizozemsko": "nl", "Netherlands": "nl", "NED": "nl",
  "Nový Zéland": "nz", "New Zealand": "nz", "NZL": "nz",
  "Panama": "pa", "PAN": "pa",
  "Paraguay": "py", "PAR": "py",
  "Portugalsko": "pt", "Portugal": "pt", "POR": "pt",
  "Qatar": "qa", "QAT": "qa",
  "Saudská Arábie": "sa", "Saudi Arabia": "sa", "KSA": "sa",
  "Skotsko": "gb-sct", "Scotland": "gb-sct", "SCO": "gb-sct",
  "Senegal": "sn", "SEN": "sn",
  "Jižní Afrika": "za", "South Africa": "za", "RSA": "za",
  "Španělsko": "es", "Spain": "es", "ESP": "es",
  "Tunisko": "tn", "Tunisia": "tn", "TUN": "tn",
  "Turecko": "tr", "Türkiye": "tr", "TUR": "tr",
  "Uruguay": "uy", "URU": "uy",
  "Uzbekistán": "uz", "Uzbekistan": "uz", "UZB": "uz",
  "Kongo DR": "cd", "Congo DR": "cd", "COD": "cd",
}

export function getFlagPath(teamName: string): string {
  const code = teamFlags[teamName] || teamName.toLowerCase().slice(0, 2)
  return `/flags/${code}.webp`
}

export function getFlagCode(teamName: string): string {
  return teamFlags[teamName] || teamName.toLowerCase().slice(0, 2)
}

export function getFlag(teamName: string): string {
  return getFlagPath(teamName)
}

// Mapování anglický název → český název pro zobrazení
export const countryNamesCs: Record<string, string> = {
  "Czech Republic": "Česko",
  "Czechia": "Česko",
  "CZE": "Česko",
  "Sweden": "Švédsko",
  "SWE": "Švédsko",
  "Canada": "Kanada",
  "CAN": "Kanada",
  "United States": "USA",
  "Switzerland": "Švýcarsko",
  "SUI": "Švýcarsko",
  "Finland": "Finsko",
  "FIN": "Finsko",
  "Germany": "Německo",
  "GER": "Německo",
  "Denmark": "Dánsko",
  "DEN": "Dánsko",
  "Norway": "Norsko",
  "NOR": "Norsko",
  "Slovakia": "Slovensko",
  "SVK": "Slovensko",
  "Slovenia": "Slovinsko",
  "SLO": "Slovinsko",
  "Italy": "Itálie",
  "ITA": "Itálie",
  "Austria": "Rakousko",
  "AUT": "Rakousko",
  "Latvia": "Lotyšsko",
  "LAT": "Lotyšsko",
  "Hungary": "Maďarsko",
  "HUN": "Maďarsko",
  "Great Britain": "Velká Británie",
  "GBR": "Velká Británie",
  "Russia": "Rusko",
  "RUS": "Rusko",
  "Poland": "Polsko",
  "POL": "Polsko",
  "France": "Francie",
  "FRA": "Francie",
  "Japan": "Japonsko",
  "JPN": "Japonsko",
  "Kazakhstan": "Kazachstán",
  "KAZ": "Kazachstán",
  "Algeria": "Alžírsko",
  "ALG": "Alžírsko",
  "Argentina": "Argentina",
  "ARG": "Argentina",
  "Australia": "Austrálie",
  "AUS": "Austrálie",
  "Belgium": "Belgie",
  "BEL": "Belgie",
  "Bosnia and Herzegovina": "Bosna a Hercegovina",
  "BIH": "Bosna a Hercegovina",
  "Brazil": "Brazílie",
  "BRA": "Brazílie",
  "Cabo Verde": "Kapverdy",
  "CPV": "Kapverdy",
  "Colombia": "Kolumbie",
  "COL": "Kolumbie",
  "Democratic Republic of the Congo": "Demokratická republika Kongo",
  "COD": "Demokratická republika Kongo",
  "Croatia": "Chorvatsko",
  "CRO": "Chorvatsko",
  "Curaçao": "Curacao",
  "CUW": "Curacao",
  "Côte d’Ivoire": "Pobřeží Slonoviny",
  "Cote d'Ivoire": "Pobřeží Slonoviny",
  "CIV": "Pobřeží Slonoviny",
  "Ecuador": "Ekvádor",
  "ECU": "Ekvádor",
  "Egypt": "Egypt",
  "EGY": "Egypt",
  "England": "Anglie",
  "ENG": "Anglie",
  "Ghana": "Ghana",
  "GHA": "Ghana",
  "Haiti": "Haiti",
  "HTI": "Haiti",
  "Iran": "Írán",
  "IRN": "Írán",
  "Iraq": "Irák",
  "IRQ": "Irák",
  "Jordan": "Jordánsko",
  "JOR": "Jordánsko",
  "Korea Republic": "Jižní Korea",
  "KOR": "Jižní Korea",
  "Mexico": "Mexiko",
  "MEX": "Mexiko",
  "Morocco": "Maroko",
  "MAR": "Maroko",
  "Netherlands": "Nizozemsko",
  "NED": "Nizozemsko",
  "New Zealand": "Nový Zéland",
  "NZL": "Nový Zéland",
  "Panama": "Panama",
  "PAN": "Panama",
  "Paraguay": "Paraguay",
  "PAR": "Paraguay",
  "Portugal": "Portugalsko",
  "POR": "Portugalsko",
  "Qatar": "Qatar",
  "QAT": "Qatar",
  "Saudi Arabia": "Saudská Arábie",
  "KSA": "Saudská Arábie",
  "Scotland": "Skotsko",
  "SCO": "Skotsko",
  "Senegal": "Senegal",
  "SEN": "Senegal",
  "South Africa": "JAR",
  "RSA": "JAR",
  "Spain": "Španělsko",
  "ESP": "Španělsko",
  "Tunisia": "Tunisko",
  "TUN": "Tunisko",
  "Türkiye": "Turecko",
  "TUR": "Turecko",
  "Uruguay": "Uruguay",
  "URU": "Uruguay",
  "Uzbekistan": "Uzbekistán",
  "UZB": "Uzbekistán",
}

export function getCzechName(teamName: string): string {
  return countryNamesCs[teamName] || teamName
}